server:
  tcp1_listen_addr: 127.0.0.101
  tcp1_listen_port: 31411
  tcp2_listen_addr: 127.0.0.103
  tcp2_listen_port: 31413

  tunnel_device:
    name: dpTcpTunServer
    ip: 10.0.0.1

logger:
  level: info